### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AyiTheDeer** [madiedinro/rodin_helpers_py#2]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

И не лечится.

**Comment by madiedinro** [comment]
Полагаю это в Windows. К сожалению у меня нет ни возможности ни желания поддерживать эту платформу. Более того данная ошибка относится не а коду библиотеки, с к установленному интерпретатору python. Опять же с win множество нюансов зависимых от того, какая сборка python используется. Полагаю самым ортодоксальным путём было бы использование Cygwin, где эта проблема должна быть само-собой решена,
